hw 6, task 1: model a local network with viruses and connections between computers in OOP style
SmirnovAlexander/homeworks_3rdsem pull request #18
Opened 2019-04-16 19:42 UTC by SmirnovAlexander

2019-06-07 14:01 UTC, yurii-litvinov requested changes
Вообще хорошо, но надо навести порядок.

2019-06-07 14:01 UTC, yurii-litvinov commented on OOP/OOP.Tests/localNetwork_tests.fs
> +                             ]
Зачем она вещественная? :)

2019-06-07 14:01 UTC, yurii-litvinov commented on OOP/OOP.Tests/localNetwork_tests.fs
> +    let ``Infect 5th computer`` () =
А я вот запустил отдельно этот тест, а он не прошёл. А потому что зависимости по данным между тестами создавать нельзя, потому что бывает параллельное исполнение, плейлисты и необходимость отладки тестов.

2019-06-07 14:01 UTC, yurii-litvinov commented on OOP/OOP/localNetwork.fs
> +    // Operation system class.
/// лучше

2019-06-07 14:01 UTC, yurii-litvinov commented on OOP/OOP/localNetwork.fs
> +        member this.infectProbability = infectProbability
Свойства в дотнете именуются с заглавной

2019-06-07 14:01 UTC, yurii-litvinov commented on OOP/OOP/localNetwork.fs
> +        let mutable IsInfected = isInfected
А поля со строчной

2019-06-07 14:01 UTC, yurii-litvinov commented on OOP/OOP/localNetwork.fs
> +        member this.isInfected = IsInfected
Всё перепутали :)

2019-06-07 14:01 UTC, yurii-litvinov commented on OOP/OOP/localNetwork.fs
> +            Console.ReadKey() |> ignore
Этот класс --- классический пример антипаттерна "God Object", надо распределить его функциональность по разным классам

2019-06-07 14:01 UTC, yurii-litvinov commented on OOP/OOP/localNetwork.fs
> +                    yield h,x
Пробел :)

2019-06-07 14:01 UTC, yurii-litvinov commented on OOP/OOP/localNetwork.fs
> +                    counter <- counter + 1
Это же какаяя-то разновидность fold, зачем же совсем на Паскаль переходить :)

2019-06-07 14:01 UTC, yurii-litvinov commented on OOP/OOP/localNetwork.fs
> +                    Console.ForegroundColor<-ConsoleColor.Red
Пробелы вокруг <- надо

2019-06-07 14:01 UTC, yurii-litvinov commented on OOP/OOP/localNetwork.fs
> +                    if ((fst pair).isInfected = true && (snd pair).isInfected = false) then
Нехорошо сравниваться с булевыми константами как будто isInfected и не возвращает и так булевое значение

2019-06-07 14:01 UTC, yurii-litvinov commented on OOP/OOP/localNetwork.fs
> +                 let random = new Random()
Random нельзя создавать каждый раз, потому что он имеет неприятное свойство инициализирвоаться текущим временем в миллисекундах. Поскольку миллисекунда --- это целая вечность, тут будет куча рандомов, возвращающих абсолютно одинаковые значения. И сборик мусора не будет этому рад, кстати

2019-06-09 17:16 UTC, SmirnovAlexander commented on OOP/OOP.Tests/localNetwork_tests.fs
> +                             ]
![image](https://user-images.githubusercontent.com/32129186/59162070-84ba5200-8af3-11e9-8404-6a389cb8b1c5.png)

2019-06-12 14:13 UTC, merged